### ISSUE TITLE
Trying to use uuid as parameter with the query builder seems to cause out of memory errors.

### ISSUE THREAD

**Issue by markbeazley** [ramsey/uuid-doctrine#11]
Sorry if this isn't the right place.

I'm using you Uuid class as an id on an entity and I'm trying to write a DQL query (trying to load sub entities in a single query) with the query builder, using the various find()/findBy() funcitons work fine, how ever if I try and use the uuid in setParameter with the type set to 'uuid_binary' I just get a 500 error for exhausted memory (I tried upping the limit to 2GB and it still happens).

`$query = $this->getEntityManager()->createQuery('SELECT c,i FROM AppBundle:Cart c join c.items i where c.id = :id')->setParameter('id', $cartId, 'uuid_binary');`

 Where $cartID is an instance of Uuid, if I remove the type parameter Doctrine just sends 'Object(Ramsey\\Uuid\\Uuid)' as the parameter to the DB, if I change the parameter to Doctrine's built in object type it sends 'C:16:"Ramsey\Uuid\Uuid":36:{6eed93c9-abbb-4ce4-b497-654f6dcab8aa}' (which I would expect) but as son as its set to uuid_binary PHP just hits its memory limit.

Closest I've found searching is I should be using Type::getType('uuid_binary') but this just results in a "Warning: Illegal offset type in isset or empty" in hasType() of 'doctrine\dbal\lib\Doctrine\DBAL\Types\Type.php', but as none of the built in Doctrine types work with that either I assume that is an out dated method.

I'm using Symfony 3.0.3, and Doctrine 2.5.4.

**Comment by ramsey** [comment]
@WouterSioen, any ideas on this?

**Comment by WouterSioen** [comment]
I haven't used this for a while, so I can't really think of anything right now.

**Comment by markbeazley** [comment]
Don't worry with a fresh pair of eyes on it this morning turns out it was something I was doing elsewhere in the code with the entity I was loading that was causing the memory issue, specifying the type as above works fine.
