### ISSUE TITLE
Release with UuidGenerator

### ISSUE THREAD

**Issue by antonienko** [ramsey/uuid-doctrine#12]
The last release doesn't include the UuidGenerator. Is it possible to create a new release that includes it?

Thanks for the good job!

**Comment by ramsey** [comment]
> The last release doesn't include the UuidGenerator.

Which version are you referring to? 2.9.0 or 3.3.0? Also, which UuidGenerator is missing? Can you post some code to show how you are using the library?

**Comment by antonienko** [comment]
I just followed the instructions at the README, but when you install from packagist without explicitly saying which version you get release 1.1.0, from february 1st. And by the history of commits seems like UuidGenerator was added in March.

I changed my composer.json to ask for dev-master and it's working, but there's no "stable" release with it.

**Comment by ramsey** [comment]
I'm sorry. I was confused about which library you were using. I thought this was a question on ramsey/uuid. You're asking for ramsey/uuid-doctrine. Apologizes. :-)

Version 1.1.0 is the correct version to use for ramsey/uuid-doctrine.

Do you get an error message? If so, what is it?

**Comment by ramsey** [comment]
I have a hunch as to what is going on. When you install ramsey/uuid-doctrine, do you also see it installing ramsey/uuid 3.3.0?

If so, when you run your code, are you getting an Exception with the message "There is no suitable CSPRNG installed on your system"?

If this is the case, can you provide more information about your system? What version of PHP? What OS?

Thanks!

**Comment by antonienko** [comment]
The exact error I get is: 
`[Doctrine\ORM\ORMException] Can't instantiate custom generator : Ramsey\Uuid\Doctrine\UuidGenerator`

And of course, if I look into vendor/ramsey/uuid-doctrine/src/ there is no UuidGenerator file, just 
`UuidBinaryType.php  UuidType.php`

**Comment by ramsey** [comment]
I see the problem now. The README.md file in the master branch is ahead of release 1.1.0 because I haven't yet released what's in master as 1.2.0, so the documentation is for new functionality that hasn't been released yet. Sorry for the confusion.

There's a simple enough solution, though. I have just released 1.2.0, which includes the UuidGenerator class.

Please update Composer and let me know if this fixes the problem. Thanks!

**Comment by antonienko** [comment]
Updated to 1.2.0 and working perfectly!

Thank you very much and keep up the good work!

**Comment by ramsey** [comment]
Great to hear!
