### ISSUE TITLE
Multiple @GeneratedValue are not possible

### ISSUE THREAD

**Issue by ghost** [ramsey/uuid-doctrine#13]
I like to do this:

``` php
    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \Ramsey\Uuid\Uuid
     *
     * @ORM\Column(type="uuid")
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="Ramsey\Uuid\Doctrine\UuidGenerator")
     */
    private $uuid;
```

**But this is not possible.** It will remove the AUTO_INCREMENT from the `id` field. More info: http://stackoverflow.com/questions/13915944/two-generated-values-in-doctrine

So please add to documentation how to use it additionally to an `id` field.

**Comment by JHGitty** [comment]
I've bypassed this issue by adding an event listener to my code. My application is based on the Symfony Framework so your code might be different.

Let's say we have ``EntityA`` and ``EntityB`` and **both** have the following code:

```php
    /**
     * @var \Ramsey\Uuid\Uuid
     *
     * @ORM\Column(type="uuid")
     */
    private $uuid;
```
(Don't forget to create ``setUuid($uuid)`` and ``getUuid()`` on the entity classes)

Event listener:
```php
<?php
namespace AppBundle\EventListener;

use AppBundle\Entity\EntityA;
use AppBundle\Entity\EntityB;
use Doctrine\Common\EventSubscriber;
use Doctrine\ORM\Event\LifecycleEventArgs;
use Ramsey\Uuid\Doctrine\UuidGenerator;

class UuidSubscriber implements EventSubscriber
{
    /**
     * @var UuidGenerator
     */
    private $generator;

    /**
     * @param UuidGenerator $uuidGenerator
     */
    public function __construct(UuidGenerator $uuidGenerator)
    {
        $this->generator = $uuidGenerator;
    }

    /**
     * {@inheritdoc}
     */
    public function getSubscribedEvents()
    {
        return [
            'prePersist',
            'preUpdate',
        ];
    }

    /**
     * @param LifecycleEventArgs $args
     */
    public function prePersist(LifecycleEventArgs $args)
    {
        $this->updateUuid($args);
    }

    /**
     * @param LifecycleEventArgs $args
     */
    public function preUpdate(LifecycleEventArgs $args)
    {
        $this->updateUuid($args);
    }

    /**
     * @param LifecycleEventArgs $args
     */
    public function updateUuid(LifecycleEventArgs $args)
    {
        $entity = $args->getEntity();

        if (!$entity instanceof EntityA
            && !$entity instanceof EntityB
        ) {
            return;
        }

        if (empty($entity->getUuid())) {
            $uuid = $this->generator->generate($args->getEntityManager(), $entity);
            $entity->setUuid($uuid);
        }
    }
}
```

This will automatically add a new UUID to the ``$uuid`` field of the entities ``EntityA`` and ``EntityB`` if no UUID has been manually set.

**Comment by ramsey** [comment]
Thanks for the update. I wasn't ignoring this issue, though I should have spoken up to acknowledge that I saw it. I just wasn't sure exactly how to address it, but your solution looks good.

**Comment by JHGitty** [comment]
@ramsey It would be nice if this would be added to the documentation.

Another easier solution would be to use Lifecycle Events directly in the entity class:
http://doctrine-orm.readthedocs.io/en/latest/reference/events.html#lifecycle-callbacks

**Comment by ramsey** [comment]
@JHGitty, would you like to send a PR to update the README with examples? You might be able to explain the issue better than I can.

**Comment by althaus** [comment]
Is there a solution if you're mixing a fixed primary key property with another auto increment (sequence) property? I cannot get this sorted out.

**Comment by Inwerpsel** [comment]
Can this issue be reopened? It is still not possible (at least in certain cases) to add a second GeneratedValue when the database already exists and is already populated. This results in the "doctrine:schema:update" command trying to alter the existing GeneratedValue column.

Imagine you have a populated database with this schema:
```
/**
* @ORM\Entity
**/
class MyEntity
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
    **/
    private $id;
}
```

You then add a new GeneratedValue column to it.
```
/**
* @ORM\Entity
**/
class MyEntity
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
    **/
    private $id;
    /**
     * @var int
     *
     * @ORM\Column(name="public_id", type="uuid")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="Ramsey\Uuid\Doctrine\UuidGenerator")
    **/
    private $publicId;

}
```

Then you try to update your schema:
```/var/www bin/console doctrine:schema:update --force```

This fails with following message:
```
SQLSTATE[HY000]: General error: 1833 Cannot change column 'id': used in a foreign key constraint 'FK_2D25F90A9E6B1585' of table 'mydb.other_table'
```

If I let the command dump the SQL then I see that it tries to do an alter statement on the id column, even though from the SQL you can see that it didn't change at all.
```/var/www bin/console doctrine:schema:update --dump-sql```
```
ALTER TABLE my_entity ADD public_id CHAR(36) NOT NULL COMMENT '(DC2Type:uuid)', CHANGE id id INT NOT NULL;
```

If I remove GeneratedValue from the public_id column then everything is fine.
```
/**
* @ORM\Entity
**/
class MyEntity
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
    **/
    private $id;
    /**
     * @var int
     *
     * @ORM\Column(name="public_id", type="uuid")
     * @ORM\Id
    **/
    private $publicId;

}
```
```/var/www bin/console doctrine:schema:update --dump-sql```
```
ALTER TABLE my_entity ADD public_id CHAR(36) NOT NULL COMMENT '(DC2Type:uuid)';
```

**Comment by Inwerpsel** [comment]
Might be caused by or related to https://github.com/doctrine/doctrine2/issues/7215

**Comment by metalmini** [comment]
> Might be caused by or related to [doctrine/orm#7215](https://github.com/doctrine/orm/issues/7215)

Related, yes. Not caused, and yes, this is still an issue.

**Comment by falkenhawk** [comment]
you may use https://github.com/KnpLabs/DoctrineBehaviors/blob/master/docs/uuidable.md instead

**Comment by alebec** [comment]
Why don't use a simple constructor to initialise uuid ? 
```
    public function __construct()
    {
        $this->uuid = Uuid::uuid4();
    }
```

**Comment by pluk77** [comment]
@alebec Have you tried using the constructor for this in a production system, and what would the possible downsides be compared to using a subscriber?

**Comment by Arnaud-J** [comment]
The [proposed solution](13#issuecomment-219260311) seems correct to me (although I had to explicitly do `new UuidGenerator()` rather than injecting it because of `argument "$uuidGenerator" of method "__construct()" references class "Ramsey\Uuid\Doctrine\UuidGenerator" but no such service exists`, probably due to some changes in the lib).

Nevertheless, as mentionned by @alebec, one could directly use `Uuid::uuid4();` because this is basically all the generator does. This makes the generator quite useless in this particular case, so I think the doc should reflect that and redirect to [ramsey/uuid](https://github.com/ramsey/uuid) instead with a `prePersist` ready-to-use example.
@ramsey If this seems fine by you, I am ready to pull-request this documentation change

As for @pluk77 question whether using the constructor rather than the event listener/subscriber system, I have no answer for this now but I would _feel_ more comfortable with a `prePersist` listener.

**Comment by ramsey** [comment]
@Arnaud-J, please feel free to open a PR. Thanks!
