### ISSUE TITLE
No result found using uuid_binary_ordered_time

### ISSUE THREAD

**Issue by bogdaniel** [ramsey/uuid-doctrine#148]
Hello, I'm trying to create a doctrine filter that would filter my results based on what uuid I'm setting from the user auth.

First I'm converting my string to an uuid object that I pass it to my query:
`$uuid = Uuid::fromString('88e3fad0-a4aa-11ea-9abf-080027706c79');`
And in my filter
`return $targetTableAlias . '.user_uuid= "' . $this->context->getUuid() . '"';`
where getUuid() would return the Uuid object from ramsey.
The filter then adds to my query:
`WHERE t0.id = ? AND ((t0.user_uuid= "88e3fad0-a4aa-11ea-9abf-080027706c79"))`
Which would work if my column would be char but on binary column it doesn't work at all yet I've seen that if I use find it will get converted to binary in the query.

**Comment by havvg** [comment]
While using the binary column, you need to compare with the binary UUID, not the string representation, for example:

```php
/* @see \Ramsey\Uuid\Codec\OrderedTimeCodec::encodeBinary */
$bytes = $uuid->getFields()->getBytes();
$id = $bytes[6].$bytes[7].$bytes[4].$bytes[5].$bytes[0].$bytes[1].$bytes[2].$bytes[3].substr($bytes, 8);

$queryBuilder->setParameter(':id', $id, Types::BINARY);
```

**Comment by Dallas62** [comment]
Hi @bogdaniel,

I was also stuck into this situation, you can precise the type as third parameter.
```php
    return $this->createQueryBuilder('u')
      ->andWhere('u.id = :value')
      ->setParameter('value', $value, 'uuid_binary_ordered_time')
      ->getQuery()
      ->getOneOrNullResult();
```

Replace `uuid_binary_ordered_time`  by the value of your type from `config/packages/doctrine.yaml` in `doctrine.dbal.types`.

**Comment by milanobrtlik** [comment]
Hi @bogdaniel 
do you have production ready idea how to set parameter type automatically if we are working with ids? My idea is override `QueryBuilder::setParameter` method. Check if we are dealing with ids and if yes, then add `uuid_binary_ordered_time` type. But it's really silly, because my colleagues are not aware that their parameter names MUST contain `id` string. Better solution can be checking the column type in DQL, but i can't find how to do that yet.

**Comment by Dallas62** [comment]
Hi @milanobrtlik 
I don't know. It's working and I don't need an auto-detection of the type on my project 😉

**Comment by m1ndgr3p** [comment]
@milanobrtlik you can implement dbal connection wrapper and add some if statements to detect uuid type parameters in `getBindingInfo()`. this would work for doctrine and codeception if you use one. there is minimum one "but"... you have to maintain this wrapper
