### ISSUE TITLE
Uuid on api-platform as Primary Key

### ISSUE THREAD

**Issue by dadangnh** [ramsey/uuid-doctrine#149]
When we use Uuid as Primary Key on API-Platform Project, it shows:

Can't instantiate custom generator : UuidGenerator in . (which is being imported from "/storage/dadangnh/Projects/djp-iam/config/routes/api_platform.yaml"). Make sure there is a loader supporting the "api_platform" type.

![Screenshot from 2020-07-13 22-45-37](https://user-images.githubusercontent.com/9269195/87324656-983bb600-c55a-11ea-991e-76612181faff.png)

On the entity, $id was like this:
```php

    /**
     * @var UuidInterface
     *
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     */
    private $id;
```

**Comment by burned42** [comment]
@dadangnh I also tried this just a few days ago and for me it worked. Did you also add an import statement for the generator class?

```php
use Ramsey\Uuid\Doctrine\UuidGenerator;
```

**Comment by dadangnh** [comment]
> @dadangnh I also tried this just a few days ago and for me it worked. Did you also add an import statement for the generator class?
> 
> ```
> use Ramsey\Uuid\Doctrine\UuidGenerator;
> ```

aah this one solve the problem.. I only import the Ramsey\Uuid\UuidInterface but forgot the UuidGenerator..

Thank you, it's worked now
