### ISSUE TITLE
Documentation Suggestion - Polyfill BIN_TO_UUID UUID_TO_BIN

### ISSUE THREAD

**Issue by michaeldnelson** [ramsey/uuid-doctrine#151]
First off, thank you, I install your Uuid package in almost every project, first time for uuid-doctrine though.

It was unclear to me that ouuid_to_uuid and uuid_to_ouuid were swapping byte order by default and were intended exclusively for uuid_binary_ordered_time.  Such a function would be useful for both uuid_binary_ordered_time and uuid_binary.  

MySql 8+ provides UUID_TO_BIN and BIN_TO_UUID that replicate this functionality including byte order swap when passing true as a second parameter.   There is an example of a polyfill [here](https://stackoverflow.com/questions/28251144/inserting-and-selecting-uuids-as-binary16).

I was able to sort it out eventually but I thought I would mention it as an area of confusion for me.  If you would like help updating docs and think this would be beneficial to your project I'm happy to submit a PR.

Thanks again :)

**Comment by ramsey** [comment]
This sounds like a good addition to the documentation. Feel free to submit a PR. Thanks!

**Comment by michaeldnelson** [comment]
I have submitted a PR.  I attempted to emulate the existing documentation as closely as possible.  If you would like me to make any changes I am happy to do so, and thanks again.
