### ISSUE TITLE
Doctrine array type and ramsey/uuid 4.1

### ISSUE THREAD

**Issue by HugoMestreCL** [ramsey/uuid-doctrine#154]
Hey,
first let me thank you for these great libraries before everything else.

Recently we started having issues after an upgrade from version 4.0.1 to version 4.1.0 of ramsey/uuid and it was because we're saving doctrine array results to an array type property on our Entity, which doctrine translates to a longtext type column to store the serialized array. So what was happening on our app was that the serialization string, on the database column, was getting truncated as soon as the raw bytes of the time ordered uuid started and that would then lead to an unserialization exception.

There's a few things in the mix here, first i'm not sure that doctrine array type should translate to a longtext column, but since it is, isn't possible that this change is a bigger change that at first it seemed to be? Is this enough to qualify as a BC break?

To be clear, what was a text string as a serialization result in version 4.0.1 of ramsey/uuid is now a string with raw bytes since version 4.1.0.

**Comment by tonyellow** [comment]
I have the same problem

**Comment by 537mfb** [comment]
see if the discussion in uuid/#329  helps

**Comment by ramsey** [comment]
Upgrading to ramsey/uuid 4.2 should fix this. If not, please let me know.
