### ISSUE TITLE
Use VARBINARY(16) instead of BINARY

### ISSUE THREAD

**Issue by ezerw** [ramsey/uuid-doctrine#157]
Hi, I'm working in migrate an old app to Laravel 8 with doctrine 2 and I'm using this package to store an entity ID as binary and retrieve the uuid as string.

The problem I have now is that the existing table is using `VARBINARY(16)` instead of `BINARY` like this package use, I need to maintain the original table structure as it's huge but because of the difference I'm having some issues querying as the types are not the same.

Is there a way of define `VARBINARY(16)` instead?

Config I'm using (that works awesome with a `BINARY` field):
```php
'custom_types' => [
    'uuid' => Ramsey\Uuid\Doctrine\UuidType::class,
    'uuid_binary' => Ramsey\Uuid\Doctrine\UuidBinaryType::class,
],

'mapping_types' => [
    'uuid' => 'uuid',
    'uuid_binary' => 'binary',
],
```

**Comment by Ocramius** [comment]
> Is there a way of define `VARBINARY(16)` instead?

You will need to extend `UuidBinaryType` and override `UuidBinaryType::getSQLDeclaration()` here.

**Comment by ramsey** [comment]
Thanks, @Ocramius, for helping out!
