### ISSUE TITLE
data type for validation with Doctrine

### ISSUE THREAD

**Issue by desnudopenguino** [ramsey/uuid-doctrine#158]
in the README, there is a sample of using the uuid as an id variable type. is there a way to set the type for the getter. for example `public function getId(): ?uuid` in the definition.

**Comment by Ocramius** [comment]
Send a patch (to be reviewed/discussed), please: the description here is a bit too small to make sense of what you actually want, sorry.

**Comment by ramsey** [comment]
Agreed. I'm not sure if this is asking whether it's possible to set the return type for the getter (in which case, the answer is "yes," you may do that) or if the example in the README can be updated (this answer is also "yes," but I'll hold off on updating it until I remove support for PHP 5 😄 ).
