### ISSUE TITLE
Symfony form validation error

### ISSUE THREAD

**Issue by fmonts** [ramsey/uuid-doctrine#16]
I'm using a uuid_binary field as primary key for a Doctrine Entity:

```
class Site
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="UUID")
     * @ORM\Column(type="uuid_binary")
     */
    private $id;

    ...
} 
```

I need to build a form for another entity which has that entity in a ManyToOne relation. 

So I added, in my form builder, an EntityType as follows:

```
$builder->add('site')
```

Everything works, the HTML select has the uuids as keys, but when I submit the form I get this validation error:

> Symfony\Component\Validator\ConstraintViolation
> Object(Symfony\Component\Form\Form).children[site] = 4a41b3c4-4299-11e6-b562-fc3fdb5f816d
> 
> Caused by:
> Symfony\Component\Form\Exception\TransformationFailedException
> Unable to reverse value for property path "site": The choice "4a41b3c4-4299-11e6-b562-fc3fdb5f816d" does not exist or is not unique
> 
> Caused by:
> Symfony\Component\Form\Exception\TransformationFailedException
> The choice "4a41b3c4-4299-11e6-b562-fc3fdb5f816d" does not exist or is not unique

Any idea about how to solve this?

**Comment by ramsey** [comment]
Is the form submitting a UUID and attempting to do a database lookup based on that ID? If so, check to make sure the form isn't using the string version of the UUID when trying to do the database lookup. It needs to use the binary version of the UUID.

**Comment by ramsey** [comment]
@fmonts Were you able to solve this?

**Comment by juliusstoerrle** [comment]
I got the same Problem. The Form is using the string and not the binary Version of the UUID but i wasn't yet able to change that.

**Comment by ramsey** [comment]
@juliusstoerrle I'll reopen the issue, but I need more information in order to help solve this. Can you put together a short, reproducible example that you can paste here?

**Comment by juliusstoerrle** [comment]
Jep I will

**Comment by juliusstoerrle** [comment]
Do you just want the classes or a complete symfony set up?
--------------------------------------------------------
In my controller i generate just a basic form via the form builder to edit/create a MembershipStatusTransition object. It contains the ID as a hidden field and the $from field as a EntityType.

**The Objects for the example:**
The Transition objects holds the Membership Object in a ManyToOne Relationship aka. is the many side. 
It actually has a to (MembershipStatus) property as well but I removed it for this example.
```
<?php
declare(strict_types = 1);

namespace Core\Domain\Model\MembershipStatus;

use Core\Domain\Service\UuidTimeOrderedGenerator;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="membershipstatus_transition")
 */
class MembershipStatusTransition
{
    /**
     * @var \Ramsey\Uuid\Uuid
     *
     * @ORM\Id
     * @ORM\Column(type="uuid_binary_ordered_time")
     */
    private $id;

    /**
     * @var MembershipStatus
     *
     * @ORM\ManyToOne(targetEntity="Core\Domain\Model\MembershipStatus\MembershipStatus")
     */
    private $from;

    public function __construct()
    {
        $generator = new UuidTimeOrderedGenerator();
        $this->id = $generator->generate();
    }

    /**
     * @return \Ramsey\Uuid\Uuid
     */
    public function getId(): \Ramsey\Uuid\Uuid
    {
        return $this->id;
    }

    /**
     * @param \Ramsey\Uuid\Uuid $id
     */
    public function setId(\Ramsey\Uuid\Uuid $id): void
    {
        $this->id = $id;
    }

    /**
     * @return MembershipStatus
     */
    public function getFrom(): MembershipStatus
    {
        return $this->from;
    }

    /**
     * @param MembershipStatus $from
     */
    public function setFrom(MembershipStatus $from): void
    {
        $this->from = $from;
    }

}
```

The Membership Status is what gets selected in the ManyToOne relation. It consist of a UUID as PK plus some Metadata (Title, Description etc.)
```

<?php
declare(strict_types = 1);

namespace Core\Domain\Model\MembershipStatus;

use Core\Domain\Service\UuidTimeOrderedGenerator;
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\UuidInterface;

/**
 * @ORM\Entity
 * @ORM\Table(name="membershipstatus")
 */
class MembershipStatus
{
    /**
     * @var \Ramsey\Uuid\Uuid
     *
     * @ORM\Id
     * @ORM\Column(type="uuid_binary_ordered_time")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=100, nullable=false)
     */
    private $title;

    public function __construct()
    {
        $generator = new UuidTimeOrderedGenerator();
        $this->id = $generator->generate();
    }

    /**
     * @return UuidInterface
     */
    public function getId(): UuidInterface
    {
        return $this->id;
    }

    /**
     * @param UuidInterface $id
     */
    public function setId(UuidInterface $id): void
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * @param string $title
     */
    public function setTitle(string $title): void
    {
        $this->title = $title;
    }

}
```

**Comment by ramsey** [comment]
Thank you for the details. I'll take a look and see what I can find.

**Comment by mintobit** [comment]
@juliusstoerrle Hey. What symfony version are you using? Posting Controller (or whatever place you are using it) code and Form definition would help as well.

[This](https://github.com/symfony/symfony/issues/16486) and [this](https://github.com/symfony/symfony/issues/14025) might help

**Comment by Jean85** [comment]
If the issue is that it uses a string version for the uuid instead of the binary one, you should either use data transformers, or specify a custom query builder object for the query, using the querybuilder form option, see: https://symfony.com/doc/current/reference/forms/types/entity.html#query-builder

**Comment by juliusstoerrle** [comment]
Sorry for being offline for so long,
Symfony Version is 3.3.6; Doctrine/Orm is 2.5.10;

@Jean85 I tried various forms of data transformers non worked, i tested the form with a specified custom query builder with no change as well, would you be able to please make a short example how i should set up the builder?

I think this issue might has the same roots as #18, but I'm not yet sure on how to use that solution in a symfony form?

**Comment by juliusstoerrle** [comment]
One of the form definitions:

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('id',HiddenType::class, ['disabled' => true])
            ->add(
                $builder
                    ->create('from', EntityType::class, [
                        'class' => 'Core\Domain\Model\MembershipStatus\MembershipStatus',
               
                        'choice_label' => 'title'
                    ])
                    //->addViewTransformer(new StringToStatusTransformer($this->em
        ));
        $builder->get('id')->addModelTransformer(new StringToUuidTransformer());
        dump($builder);
    }

The StringToUuidTransformer is able to transform a UUID inside TextField but not when it is inside an drop down (select)

**Comment by meistersoda** [comment]
Is there any update? I have the same problem.

`            $builder->add('in_reply_to', EntityType::class, ['class' => 'CommentsBundle:Comment'])`

where Comment is referenced by an uuid_binary_ordered_time

I am serializing the uuid as a string and want to pass it with json to the form as 'in_reply_to' parameter - also as a json string. 

What is the best practice to do this? I want to achive something like this

{
        "comment": "Test",
        "in_reply_to": "533b05de-ebd6-11e7-92bb-0220642b0501"
}

Or is the only way to pass it with TextType and validate with a custom validator?

**Comment by ramsey** [comment]
I’ve been unable to reproduce this issue. I will ask around and see if others are able to help.

**Comment by meistersoda** [comment]
It seems related to #18 

If I call
`$this->getDoctrine()->getManager()->getRepository('CommentsBundle:Comment')->findOneById($request->request->get('in_reply_to'))` 
symfony generates a query with id = "" ... and seems to use bytes.

Validation by EntityType creates a query with id IN (...) and does not seem to use bytes. 
Maybe its caused by MariaDB.

**Comment by Holicz** [comment]
Sorry to revive this old thread, but I have better solution than the custom `UuidEntityType` proposed by @umpirsky (thanks for that btw) and people reading this thread may be interested.

Only thing you have to do is pass your entity repository into the form type and pass choices inside with `$repository->findAll();`.

Like this:
```php
final class SomeFormType extends AbstractType
{
    private SportRepository $sportRepository;

    public function __construct(
        SportRepository $sportRepository
    ) {
        $this->sportRepository = $sportRepository;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add(
                'sport',
                EntityType::class,
                [
                    'required' => true,
                    'class' => Sport::class,
                    'choice_label' => 'name',
                    'label' => 'Sport',
                    'choices' => $this->sportRepository->findAll(),
                ]
            );
    }
}
```

**Comment by pluk77** [comment]
> [ORMQueryBuilderLoader.php](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/Form/ChoiceList/ORMQueryBuilderLoader.php#L75) knows only about `uuid` and `guid`, but not about `uuid_binary_ordered_time`. 

Seeing that the Doctrine Bridge only caters for a limited amount of types for which it is using the ConvertToDatabaseType() function, the correct solution is probably to open an issue and create a PR for that code on the symfony side and ensure that all non-integer types are properly handled.

As a work-around, if the application only uses one type of uuid, a solution might be not to change the name of the doctrine type and stick with the name uuid. Than use the configs to link the doctrine uuid type to the correct Ramsey UUID type.

If this is a proper solution, a PR to update the Ramsey documentation to advice not to change the doctrine uuid type name is all that is needed.

ramsey_uuid_doctrine.yaml:
```yaml
doctrine:
    dbal:
        types:
            uuid: 'Ramsey\Uuid\Doctrine\UuidBinaryType'
```

@ramsey Can you think of any downsides to sticking to the uuid name and just pointing it to the UuidBinaryType?
