### ISSUE TITLE
doctrine.yaml configuration issue

### ISSUE THREAD

**Issue by vmdumitrache** [ramsey/uuid-doctrine#160]
I've had an issue when trying to configure a Symfony application using this package and `doctrine/orm 2.8`. The error which gets thrown is: 
```bash
Unrecognized option "uuid_binary_ordered_time" under "doctrine.dbal.types.mapping_types". Available options are "class", "commented".
```
Looking at the doctrine yaml reference, it seems that the `doctrine.dbal.types.mapping_types` parameter has been removed in `2.8`. Omitting it from the `doctrine.yaml` configuration appears to fix the issue.

I am not entirely sure if this would be 100% correct. As of now, all of the testing I've done shows that everything is linked up appropriately. I've taken the liberty of updating README.md and creating a PR for it (#159).

**Comment by Ocramius** [comment]
`doctrine.dbal.types.mapping_types` is something defined by `doctrine/doctrine-bundle`, not `doctrine/orm` - check your dependency graph.
