### ISSUE TITLE
There is  a bug in MariaDB 10.5.9, extremly slowing queris with UUID in binary form

### ISSUE THREAD

**Issue by forgie1** [ramsey/uuid-doctrine#162]
I created bugrepport in MariaDB: https://jira.mariadb.org/browse/MDEV-25020

I use uuid_binary.
There is automatic conversion from big endian to small endian managed by uuid-doctrine I guess.

Is there a way how to switch temporarily type of how doctrine request DB? So we could do a workaround this BUG in newest MariaDB?
I mean that doctrine would request IDs in HEX form, not the binnary. So ID would be sent to DB by queries in HEX form  `0x11e6a2ad166fc342abde002590a2360a`, not the `-$p#z` row binary form.

MariaDb 10.5.9 is with this binary form of ID requests 10x slower currently, and that causes huge problem with the performance.

**Comment by Ocramius** [comment]
If this is an upstream bug, I'm not sure this library should have any workaround for it: the fix should come from upstream, instead of propagating workarounds across the whole toolchain.

**Comment by ramsey** [comment]
Closing, since there's nothing I can do to correct this.
