### ISSUE TITLE
doctrine.dbal.default_connection is set to 'default' and cannot be changed anymore

### ISSUE THREAD

**Issue by yourithielen** [ramsey/uuid-doctrine#169]
## Description
When using ramsey/uuid-doctrine changing `doctrine.dbal.default_connection` in `config/packages/doctrine.yml` has no effect anymore.

## Steps to reproduce
When I register the type `Ramsey\Uuid\Doctrine\UuidType` in `ramsey_uuid_doctrine.yaml` I noticed `doctrine.dbal.default_connection` gets set to 'default'. I verified this when running `bin/console debug:config doctrine`, the value becomes `default`, ignoring the value in `config/packages/doctrine.yml`

## Environment details

- version of this package: *1.8.0*
- PHP version: *7.3.18*
- OS: *Ubuntu 16*

**Comment by ramsey** [comment]
Sorry for the delay in looking into this. Is this still an issue? If so, it is specific to this library?

**Comment by yourithielen** [comment]
Unfortunatly not able to dive into this anymore, I'd suggest closing this.
