### ISSUE TITLE
Deprecation notice after updating from Symfony 5.3 to 5.4

### ISSUE THREAD

**Issue by tarlepp** [ramsey/uuid-doctrine#171]
## Description
I notice indirect deprecation notice after I updated from Symfony 5.3 to 5.4

```
Method "Doctrine\DBAL\Types\Type::convertToPHPValue()" might add "mixed" as a native return type declaration in the future. Do the same in child class "Ramsey\Uuid\Doctrine\UuidBinaryOrderedTimeType" now to avoid errors or add an explicit @return annotation to suppress this message.
```

## Steps to reproduce

1. Create new Symfony project that is using version 5.4 
2. Add this library as a dependency
3. Create an entity that creates UUID V1 on entity construct

## Expected behavior

No deprecations notices.

## Environment details
- version of this package: 1.8.0
- PHP version: 8.0.13
- OS: docker linux from php:8.0.13-fpm

**Comment by Evgeny1973** [comment]
Have same message
`Method "Doctrine\DBAL\Types\Type::getSQLDeclaration()" might add "string" as a native return type declaration in the future. Do the same in child class "Ramsey\Uuid\Doctrine\UuidBinaryType" now to avoid errors or add an explicit @return annotation to suppress this message.`

**Comment by ruudk** [comment]
PR to fix the issue https://github.com/ramsey/uuid-doctrine/pull/173
