### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by ruudk** [ramsey/uuid-doctrine#176]
Could you please provide a new tagged release?

Currently getting this deprecation in my console and test logs:
```
Method "Doctrine\DBAL\Types\Type::getSQLDeclaration()" might add "string" as a native return type declaration in the future. Do the same in child class "Ramsey\Uuid\Doctrine\UuidBinaryType" now to avoid errors or add an explicit @return annotation to suppress this message.
```

A new release would solve that. Thanks 💙 

https://github.com/ramsey/uuid-doctrine/compare/1.8.0...main

**Comment by ramsey** [comment]
Thanks for opening this issue to remind me. 😃 

I've tagged release 1.8.1.
