### ISSUE TITLE
UuidBinary (or array of uuid) as parameter for QueryBuilder

### ISSUE THREAD

**Issue by grachevko** [ramsey/uuid-doctrine#18]
When doctrine make query with array of uuids as parameter, every uuid cast to string. 
Result match nothing, because need cast to Bytes. 
Is only to extend Uuid class and replace behavior of __toString() method?

**Comment by NavyCoat** [comment]
I think It can have something with this issue in Doctrine https://github.com/doctrine/doctrine2/issues/4632.

I also found some other issue that can be connected to this:
https://github.com/doctrine/doctrine2/issues/2991
https://github.com/doctrine/doctrine2/issues/4632
https://github.com/doctrine/doctrine2/pull/1339
https://github.com/doctrine/doctrine2/pull/574

@grachevko Did you found any solution for this?

**Comment by grachevko** [comment]
@NavyCoat i just override method __toString() to make it return Bytes.

**Comment by oniric85** [comment]
I'm having a similar problem when using Doctrine Paginator. I think binary UUID should not be recommended as long as we have these major issues.

**Comment by grachevko** [comment]
@oniric85 this is a doctrine issue, because it can't handle array of objects. Only array of int or strings. 
I guess this issue not actual for PostgreSQL database. Because it has uuid field type, which can get uuid as string and seamlessly convert it to binary.

**Comment by oniric85** [comment]
I guess I'm going to convert my mapping information to string UUID for the time beeing, running MariaDB here :)

**Comment by grachevko** [comment]
@oniric85 try to set $fetchJoinCollection as false
https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Tools/Pagination/Paginator.php#L63

**Comment by oniric85** [comment]
@grachevko that's what I'm doing in the meantime :) But this won't work for more complex queries I guess.

**Comment by ruslankovalov** [comment]
The same thing for me with EntityType in Symfony.  The entity is not found since Symfony uses IN condition in its query and doctrine turns them to string UUIDs

**Comment by fritz-gerneth** [comment]
I run into the same issue when removing entities that use table inheritance. The `JoinTablePersister` does not use proper type-mapping either. So I went ahead and replaced the `OrderedTimeCode`'s `encode` function to return the binary value. Also solved all issues with querying for an array of Uuids and such. 

Pretty effective but not the cleanest way, rather would have Doctrine handle this correctly. But given how slow-moving Doctrine is we certainly didn't want to wait for them to fix this. Only downside is that now all other code has to convert the UUIDs into readable format on their end. Fortunately for us this is only on 2 places.

**Comment by jaikdean** [comment]
Doctrine has an undocumented an more explicit way of setting parameters now, where you may specify a DBAL type for each one. That solves this issue.

Example:

```php
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Query\Parameter;

$em
    ->createQuery('SELECT b FROM \Foo\Bar b WHERE b.id = :id')
    ->setParameters(new ArrayCollection([
        new Parameter('id', $uuid, 'uuid_binary'),
    ]))
;
```

**Comment by grachevko** [comment]
@jaikdean try `'SELECT b FROM \Foo\Bar b WHERE b.id IN (:ids)'`

**Comment by jaikdean** [comment]
Touché. I've not seen a clean way to do that. This should work?

```->setParameters([
    'ids' => array_map(function ($uuid) {
        return $uuid->getBytes();
    }, $uuids),
])```

**Comment by grachevko** [comment]
This should work, but you can't do that in every cases. In vendor files for example.

**Comment by catalinbuletin** [comment]
Any solutions to this issue?

I get no results when using Doctrine's `EntityRepository::findBy($criteria)` where `$criteria['id']` contains an array of `Ramsey\Uuid\Uuid` objects.

If I pass only one id, it works fine.

Any thoughts?

**Comment by dkarlovi** [comment]
@catalinbuletin I don't think anything can be done outside Doctrine. It should use the value coming from the type's `convertToDatabaseValue`, not using `__toString`.

**Comment by meistersoda** [comment]
@catalinbuletin Are you using MariaDB?

**Comment by wtorsi** [comment]
Any news here?

**Comment by wtorsi** [comment]
Yes, i know, but this kind of case does not work in joined entities. 
The best simple solution for me was using string UUID, not binary, until custom Doctrine Type will be supported.

**Comment by manuscle** [comment]
Do you have an example of query so I could try it?

**Comment by pink6440** [comment]
Using the findBy method of the repository seems working fine with the uuid_binary_type.

**Comment by jaikdean** [comment]
@pink6440 That has always worked, because `findBy` knows what field you're comparing the UUID to, so Doctrine knows to use the binary value. When using it a `QueryBuilder`, there's no field definition to read.

**Comment by AliAmjid** [comment]
I have solved this with this 

```php    public function __toString()
    {
		 if(debug_backtrace()[1]['object'] == PDOConnection::class) {
		 	$this->getBytes();
		 } else {
		 	return $this->toString();
		 }
    }
```

Its not good solution and its magic af but there is no other was i guess.

**Comment by jaikdean** [comment]
Using `array_map()` and `Uuid::getBytes()` with "WHERE IN" won't work as of `doctrine/orm v2.6.4` (see https://github.com/doctrine/orm/issues/7830). So far, I've not found a solution to this.

**Comment by jaikdean** [comment]
As if by magic, I've just stumbled on a slightly nasty but seemingly working fix. I've extended `UuidBinaryType` to cleanly handle binary string values even when they shouldn't be passed.

```php
<?php

declare(strict_types=1);

use Doctrine\DBAL\Platforms\AbstractPlatform;
use Ramsey\Uuid\Doctrine\UuidBinaryType as BaseType;
use Ramsey\Uuid\Uuid;

/**
 * This extends the UuidBinaryType from ramsey/uuid-doctrine to work around a
 * Doctrine ORM bug introduced in v2.6.4 by overloading convertToDatabaseValue()
 * to handle values that are already binary strings.
 *
 * @see https://github.com/doctrine/orm/issues/7830
 */
final class UuidBinaryType extends BaseType
{
    public function convertToDatabaseValue($value, AbstractPlatform $platform)
    {
        // If $value is a string but isn't a valid UUID pattern, assume it's already a binary string
        if (\is_string($value) && !\preg_match('/'.Uuid::VALID_PATTERN.'/', $value)) {
            return $value;
        }

        return parent::convertToDatabaseValue($value, $platform);
    }
}
```
