### ISSUE TITLE
Incomplete example for uuid_binary

### ISSUE THREAD

**Issue by garak** [ramsey/uuid-doctrine#30]
I just tried to move from "classic" uuid to binary one, following the README (using Symfony).
It was failing with exception `Unknown column type "uuid" requested`.
I had to specify both `uuid` and `uuid_binary` types in dbal configuration, while the README is mentioning `uuid_binary` only.

**Comment by mcneely** [comment]
So, if I read you right, you already had a uuid field and you were converting it to binary_uuid? If that's the case then doctrine would need both to handle the old type properly before converting to the new. The example assumes you're starting from scratch not moving from one to another.

**Comment by garak** [comment]
Nailed it! Thanks
