### ISSUE TITLE
UUID as custom route GET parameter

### ISSUE THREAD

**Issue by AlexanderMatveev** [ramsey/uuid-doctrine#35]
I just found an unexpected behavior.

## Case 1 (works as expected):

Route definition:

`@Route("/view/{id}", defaults={"id" = null})`

Generating path:

`{{ path('app_default_view',{id:entity.id}) }}`

The example result is ok. We have our UUID in path as parameter:

> /view/cf14f49a-e7b2-49ce-b561-84658850ea3b

## Case 2 (missing something):

Route definition:

`@Route("/add")`

Generating path:

`{{ path('app_default_add',{parent:entity.id}) }}`

The example result is:

> /add

But expected result is:

> /add?parent=cf14f49a-e7b2-49ce-b561-84658850ea3b

## Fix

I just figured out that it works fine when I converting UUID object to string first while generating path:

`{{ path('app_default_add',{parent:entity.id|trim}) }}`

Now it works fine:

> /add?parent=cf14f49a-e7b2-49ce-b561-84658850ea3b

:v:

**Comment by ramsey** [comment]
The Uuid object implements the PHP [__toString() magic method](http://php.net/manual/en/language.oop5.magic.php#language.oop5.magic.tostring), so it can be automatically converted to a string in many string contexts, but there are a few where the conversion may not take place, so explicitly casting it to a string or calling `toString()` on it is the best approach.

Glad you were able to solve it!

**Comment by AlexanderMatveev** [comment]
@ramsey ok, thanks for response
