### ISSUE TITLE
UuidBinaryOrderedTimeType: configure UuidFactory

### ISSUE THREAD

**Issue by sserbin** [ramsey/uuid-doctrine#36]
What's the supposed way of configuring `UuidFactory` in `UuidBinaryOrderedTimeType`? Unless I'm missing something, seems like the only way to do this is to copy-paste the whole class modifying uuidFactory init (because `getUuidFactory` is private).

More specifically, I'd like to be able to provide a different implementation of `NodeProviderInterface` (a cached `SystemNodeProvider`)

**Comment by ramsey** [comment]
Take a look at the examples here and see if they help answer your question. If not, let me know; share some example code, and I'll try to help simplify it so you don't have to subclass`UuidFactory`. 

https://github.com/ramsey/uuid/wiki/Ramsey%5CUuid-Cookbook

**Comment by sserbin** [comment]
Apparently I was a bit lost in various `UuidFactory`'s scattered :) and wasn't looking at the code that actually generates uuids, but rather at  `UuidBinaryOrderedTimeType` (which only converts into binary representation).

Taking a closer look I think I was able to accomplish what was needed - though I'm not sure in the most appropriate way. Here is some draft code:

```php
$cachedNodeProvider = new class(new \Ramsey\Uuid\Provider\Node\SystemNodeProvider) implements \Ramsey\Uuid\Provider\NodeProviderInterface {
    private $originalProvider;
    public function __construct(\Ramsey\Uuid\Provider\Node\SystemNodeProvider $originalProvider)
    {
        $this->originalProvider = $originalProvider;
    }

    public function getNode()
    {
        if (false !== ($node = apcu_fetch('uuid_node'))) {
            return $node;
        }
        $node = $this->originalProvider->getNode();
        apcu_store('uuid_node', $node);
        return $node;
    }
};
$uuidFactory = new \Ramsey\Uuid\UuidFactory();
$uuidFactory->setTimeGenerator(new \Ramsey\Uuid\Generator\DefaultTimeGenerator(
    $cachedNodeProvider,
    new \Ramsey\Uuid\Converter\Time\PhpTimeConverter,
    new \Ramsey\Uuid\Provider\Time\SystemTimeProvider
));
\Ramsey\Uuid\Uuid::setFactory($uuidFactory);

```

Accompanied by a custom generator (as `Ramsey\Uuid\Doctrine\UuidOrderedTimeGenerator` does not use the global UuidFactory instance - I wonder why?)
```php
class DoctrineUuidOrderedTimeGenerator extends AbstractIdGenerator
{
    /**
     * @var \Ramsey\Uuid\UuidFactory
     */
    protected $factory;

    public function __construct()
    {
        $this->factory = \Ramsey\Uuid\Uuid::getFactory();

.... equal to original UuidOrderedTimeGenerator 
```

Thanks

**Comment by ramsey** [comment]
When you call `\Ramsey\Uuid\Uuid::getFactory();`, it should be using the "global" factory that's been statically set on `Uuid`. Are you setting it before `DoctrineUuidOrderedTimeGenerator` gets instantiated?

**Comment by sserbin** [comment]
> When you call \Ramsey\Uuid\Uuid::getFactory();, it should be using the "global" factory that's been statically set on Uuid

It does. But this is the modified generator; the original just instantiates the fresh factory: https://github.com/ramsey/uuid-doctrine/blob/master/src/UuidOrderedTimeGenerator.php#L18

**Comment by ramsey** [comment]
I see what you mean. There's probably a good argument here for using dependency injection here (passing in a factory) or for calling `Uuid::getFactory()` inside the `UuidOrderedTimeGenerator` instead of using `new`.

**Comment by sserbin** [comment]
> There's probably a good argument here for using dependency injection here 

That's what I thought as well - unfortunately, the orm does not seem to allow this forcefully `new`ing the passed-in generator class, see: https://github.com/doctrine/doctrine2/blob/24377156b41a5fca37b26579c28f824f779d41ef/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php#L710
and https://github.com/doctrine/doctrine2/issues/5660

This leaves the only choice of invoking `Uuid::getFactory()` in constructor - I'd submit a pull-request with this.

**Comment by ramsey** [comment]
Thanks for contributing. Your changes are in [version 1.4.1](https://github.com/ramsey/uuid-doctrine/releases/tag/1.4.1).
