### ISSUE TITLE
Querying UuidBinaryOrderedTimeType

### ISSUE THREAD

**Issue by RonRademaker** [ramsey/uuid-doctrine#39]
Hi,

I'm using the UuidBinaryOrderedTimeType as PK on my tables. Beside the benefits mentioned in the documentation regarding speed and (index) sizes, it also allows me to easily order results by the timestamp embedded in the uuid 🎉 . This got me thinking, is it also possible to query for these timestamps? For example: I'd like all records in a table with a UUID/PK generated before or after a particular moment.

Thanks!

**Comment by ramsey** [comment]
@RonRademaker I did some playing around with this, since I haven't done it before, but I was fairly certain that it was possible without making any changes to the library, and it is. :smile:

Here's an example of how this might work. Essentially, you need to create "start" and "end" UUIDs from two known times (using the `FixedTimeProvider`) and then generate bytes from them using the `OrderedTimeCodec`:

``` php
use Ramsey\Uuid\Codec\OrderedTimeCodec;
use Ramsey\Uuid\FeatureSet;
use Ramsey\Uuid\Provider\Time\FixedTimeProvider;
use Ramsey\Uuid\UuidFactory;

$startTimeProvider = new FixedTimeProvider([
    'sec' => strtotime('September 10, 2017 00:00:00'),
    'usec' => 0,
]);

$startTimeFeatureSet = new FeatureSet();
$startTimeFeatureSet->setTimeProvider($startTimeProvider);

$startTimeFactory = new UuidFactory($startTimeFeatureSet);
$startTimeFactory->setCodec(new OrderedTimeCodec($startTimeFactory->getUuidBuilder()));

// Use 0 for node and clock sequence
$startUuid = $startTimeFactory->uuid1(0, 0);


$endTimeProvider = new FixedTimeProvider([
    'sec' => strtotime('September 11, 2017 00:00:00'),
    'usec' => 0,
]);

$endTimeFeatureSet = new FeatureSet();
$endTimeFeatureSet->setTimeProvider($endTimeProvider);

$endTimeFactory = new UuidFactory($endTimeFeatureSet);
$endTimeFactory->setCodec(new OrderedTimeCodec($endTimeFactory->getUuidBuilder()));

// Use 0 for node and clock sequence
$endUuid = $endTimeFactory->uuid1(0, 0);


// Now, do your comparison in your SQL queries. Perhaps something like this:

$sql = '
    SELECT *
    FROM my_table
    WHERE BINARY id >= :start_id AND BINARY id < :end_id
    ORDER BY id ASC
';

$dbh = new \PDO('mysql:dbname=uuid_test;host=localhost', 'root', '');

$sth = $dbh->prepare($sql);
$sth->execute([
    ':start_id' => $startUuid->getBytes(),
    ':end_id' => $endUuid->getBytes(),
]);

$results = $sth->fetchAll();
```

**Comment by RonRademaker** [comment]
This looks a lot easier and more portable than the SQL concats / substr I was doing poor attempts with. Thanks!
