### ISSUE TITLE
UuidOrderedTimeType request

### ISSUE THREAD

**Issue by juliangut** [ramsey/uuid-doctrine#44]
I want ordered uuids on database to increase query performance, this can be achieved thanks to UuidBinaryOrderedTimeType but in the way you sacrifice the ability to manually query database by id field as it's a binary (creating a function feels as a horrible hack)

Could a non-binary ordered uuid type (UuidOrderedTimeType) be added?

**Comment by ramsey** [comment]
It’s possible to query the database using a binary UUID. I’m not sure how to do this in Doctrine, though.

I can provide a better example later, but for now, take a look at this other issue, which has some similar code for querying by binary values: https://github.com/ramsey/uuid-doctrine/issues/39
