### ISSUE TITLE
Solved the oci_bind_by_name(): "Invalid variable used for bind" in Oracle

### ISSUE THREAD

**Issue by ahurt2000** [ramsey/uuid-doctrine#46]
In Oracle for relationships OneToOne throw this error: oci_bind_by_name(): "Invalid variable used for bind"
It could be Solved:
return string in the "convertToPHPValue" at UuidType

**Comment by ramsey** [comment]
The purpose of `convertToPHPValue()` is to return a Uuid object representing the value that's in the database. Why is `oci_bind_by_name()` using the return value of `convertToPHPValue()`? It should be using the return value of `convertToDatabaseValue()`.

**Comment by ahurt2000** [comment]
Is Doctrine trying to hydrate an Entity (with uuid)  and a relationship. It call oci_bind_by_name.

**Comment by fduarte42** [comment]
I'm having the same issue. How did you solve it?
