### ISSUE TITLE
Notice: Array to string conversion if criteria array has no values

### ISSUE THREAD

**Issue by forgie1** [ramsey/uuid-doctrine#47]
This code

```
$ids = []
Doctrine\ORM\EntityRepository::findBy([
	'id' => $ids,
]);
```

in 1.4.2 version generates `Array to string conversion Notice` in ...\Doctrine\DBAL\Driver\PDOStatement.php:105

Previous version 1.4.1 didn't results to Notice in this case.

This happens on 10.1.21-MariaDB with last Doctrine version.

**Comment by ramsey** [comment]
Which type are you using? `UuidBinaryType` or `UuidBinaryType`?

@enumag, can you look into this? Is this possibly a result of the changes in #45? I might roll a hotfix soon that reverts those changes until I can find a resolution for this.

Thanks!

**Comment by forgie1** [comment]
Thank you for reply

I use `Ramsey\Uuid\Doctrine\UuidBinaryType::class` bytes got by `Ramsey\Uuid::uuid1()->getBytes()`.

**Comment by enumag** [comment]
Hmm... yes, this does look like something caused by #45. I'll have a closer look tomorrow.

**Comment by ramsey** [comment]
I've reverted #45 in release 1.4.3. @forgie1, please try 1.4.3 and let me know if that fixes the problem you were facing.

**Comment by forgie1** [comment]
I have used before in composer:
```
"conflict": {
    "ramsey/uuid-doctrine": "1.4.2"
}
```
Both 1.4.1 and now 1.4.3 don't throw this notice.

**Comment by enumag** [comment]
I don't think it's possible to fix this issue. However after inspecting the internals of doctrine/dbal I don't think it's worth fixing.

The main problem is in the readme of this package. I'm rather new to UUIDs so I believed that the documentation was correct which it isn't. It says that UuidType uses `CHAR(36)` (and that's obviously bad for indexing so binary type seems better at first glance). This is true for MySQL and MariaDB. However for PostgreSQL this is incorrect. UuidType will use the internal [UUID datatype](https://www.postgresql.org/docs/9.1/static/datatype-uuid.html) on PostgreSQL and it's probably safe to assume that this type could easily be even faster for indexing uuids than bytea. It should be noted that UuidBinaryType is a MySQL/MariaDB specific optimization and that UuidType is just fine for PostgreSQL.

**Comment by flaushi** [comment]
@enumag , is this still true as of today (I expect yes)?
I am deploying my project to PostgreSQL and MySQL databases and would like to have one type that is good for all database systems. Can you recommend one to me?

**Comment by enumag** [comment]
@flaushi Sorry, I'm only using PostgreSQL so I don't know what is best when using both MySQL and PostgreSQL. I would not recommend it.
