### ISSUE TITLE
General error: 1364 Field 'id' doesn't have a default value

### ISSUE THREAD

**Issue by operfildoluiz** [ramsey/uuid-doctrine#54]
Hi,

I'm having a trouble. When I perform an persist() and flush() in Symfony, I'm getting this:

> An exception occurred while executing 'INSERT INTO pedido (emissao, total, cliente_id) VALUES (?, ?, ?, ?)' with params ["2018-01-10", "100.00", "65c4002a-06e2-442b-b1da-61197f73ba3b"]:
> 
> SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value

My annotation is the same in all entities, but in this one (specifically), Doctrine can not create auto id:

```
    /**
     * @var \Ramsey\Uuid\Uuid
     *
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="Ramsey\Uuid\Doctrine\UuidGenerator")
     */
    protected $id;
```

As the field ID is generated automatically, this error appears to make no sense.

How can I force Doctrine to "understand" the UUID field?

**Comment by rajiv180984** [comment]
Edit this file /etc/mysql/mysql.conf.d/mysqld.cnf

add the below statement under [mysqld]

sql_mode =

This is working perfectly for me.

**Comment by reiarseni** [comment]
I had the same problem because I added another auto generated field to the same entity

```php
/**
 * @var \Ramsey\Uuid\Uuid
 *
 * @ORM\Id
 * @ORM\Column(type="uuid", unique=true)
 * @ORM\GeneratedValue(strategy="CUSTOM")
 * @ORM\CustomIdGenerator(class="Ramsey\Uuid\Doctrine\UuidGenerator")
 */
protected $id;

/**
 * @var integer
 *
 * @ORM\Column(name="consecutive", type="integer", nullable=true)
 * @ORM\GeneratedValue(strategy="AUTO")
 */
private $consecutive;
```
Solved the problem by removing the **second auto-generated field**

The problem is caused by: Currenly Doctrine does not support more than one autogenerated field in single entity. If there are 2 fields Doctrine will generate value for the last one and left first field with default value (null if not specified).
