### ISSUE TITLE
If no dash

### ISSUE THREAD

**Issue by GuigZ-** [ramsey/uuid-doctrine#55]
Hey,

Before, i like your lib ❤️ .

If i use uuid with no dash, your validation throw error.

Your pattern is : `^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$`

With no dash, your pattern is wrong. To Work you need "?" after dash.

Thanks for you job.

BR

**Comment by ramsey** [comment]
The string representation of a UUID uses dashes. Otherwise, it looks no different from an MD5 hash.

The formal definition of the string representation is in [RFC 4122 § 3](https://tools.ietf.org/html/rfc4122#section-3), and the use of dashes is not optional.

**Comment by GuigZ-** [comment]
Okay, thanks for you response (:
