### ISSUE TITLE
When using this type schema tools always thinks that schema is not up-to-date

### ISSUE THREAD

**Issue by jkuchar** [ramsey/uuid-doctrine#6]
Then I create entity with you uuid type, for every use Doctrine schema tools generates this king of "update" SQL:

````sql
ALTER TABLE table ALTER id_table TYPE UUID;
ALTER TABLE table ALTER id_table DROP DEFAULT;
````

**Comment by ramsey** [comment]
@marijn or @WouterSioen, would either of you mind taking a look at this? Thanks!

**Comment by marijn** [comment]
Yeah, this is a bug in Doctrine itself if I'm not mistaken.

**Comment by marijn** [comment]
I think it's this one: http://www.doctrine-project.org/jira/browse/DBAL-63

**Comment by ramsey** [comment]
That looks like it was resolved in November 2010. Is it still an issue in Doctrine?

**Comment by marijn** [comment]
Not sure. What is the version of Doctrine you're on @jkuchar?

**Comment by WouterSioen** [comment]
Normally, the SQL Comment hint should fix this issue. @jkuchar what kind of database are you using this on?

**Comment by jkuchar** [comment]
Guys! I‘m sorry, my mistake. I was trying to override doctrine guid type with uuid which went wrong.

**Comment by WouterSioen** [comment]
glad you found it :+1:
