### ISSUE TITLE
How to use properly `findBy` uuid method in doctrine

### ISSUE THREAD

**Issue by DyaGa** [ramsey/uuid-doctrine#70]
Hi. I'm having a problem with using `findOneBy` doctrine method (MySQL). 
The field `uuid` in database is of type `binary` and in ORM config the type is `uuid_binary`.
Example:

```php
$uuid = 'b154a022-e378-41ea-bf88-309da91e874d'; // Existed UUID value in the table
$person = $repository->findOneBy(['uuid' => $uuid]); // Returns null instead of existed data
```

From the logs I see that doctrine generates next query and it returns empty result:

```sql
SELECT t0.uuid AS uuid_1
FROM person t0
WHERE t0.uuid = '\xB1T\xA0\"\xE3xA꿈0\x9D\xA9\x87M'
LIMIT 1
```

But, the query works if I use it like this:

```sql
SELECT t0.uuid AS uuid_1
FROM person t0
WHERE t0.`uuid` = x'b154a022e37841eabf88309da91e874d'
LIMIT 1
```

So, the question. How to use `findOneBy` UUID method in doctrine in a proper way?

**Comment by ramsey** [comment]
Try converting the UUID into a `Ramsey\Uuid\Uuid` object when using it in `findOneBy`:

``` php
$person = $repository->findOneBy(['uuid' => \Ramsey\Uuid\Uuid::fromString($uuid)]);
```

**Comment by DyaGa** [comment]
The same result for `Uuid::fromString`:

```sql
SELECT t0.uuid AS uuid_1
FROM oc_person t0 
WHERE t0.uuid = '\xB1T\xA0\"\xE3xA꿈0\x9D\xA9\x87M' 
LIMIT 1
```
And it's already converted here [UuidBinaryType.php#L95](https://github.com/ramsey/uuid-doctrine/blob/master/src/UuidBinaryType.php#L95).

**Comment by DyaGa** [comment]
It works now. I'm closing this issue.

**Comment by ramsey** [comment]
Can you post your solution, in case others have similar issues? Thanks!

**Comment by DyaGa** [comment]
This works as expected.

```php
$person = $repository->findOneBy(['uuid' => $uuid]);
```

It was my fault I didn't check it properly. The problem was in encoding in mysql logs.

**Comment by ramsey** [comment]
Good to hear you were able to solve it.
