### ISSUE TITLE
Use ramsey/uuid 4.x-dev

### ISSUE THREAD

**Issue by Rixafy** [ramsey/uuid-doctrine#79]
Hi! Would be cool to have __toString() function in UuidInterface, but version 4.x-dev of ramsey/uuid is not compatibile with current version ramsey/uuid-doctrine, I'm writing some extensions to Nette Framework and I'm using UuidInterface in functions (mainly exception messages, and I don't want to use toString() as it's deprecated), now I noticed IDE errors that __toString() method does not exist. I can use Uuid class instead, but UuidInterface gives user a more control.

**Comment by ramsey** [comment]
Adding `__toString()` to the interface in 3.x would cause compatibility issues with anyone implementing that interface. I am actively working on 4.x and hope to have it ready this summer.
