### ISSUE TITLE
Question: Uuid Database Type?

### ISSUE THREAD

**Issue by BallisticPain** [ramsey/uuid-doctrine#8]
@ramsey ... Thanks for a great UUID library. Been using for a bit now (couple of different places). Was thinking I would need to write the doctrine bit myself so I was happier still to find you had already done it.

However, in your documentation you mentioned that the database would store the object as a `char(36)` unless someone used the uuid_binary.

So I know Postgres (and I believe also MySQL) has a UUID database type for a column.
So as I am sitting here typing this out (using you as a rubber duckie) this may be better answered by Doctrine, but still think you may have an answer?

Are you configuring it to do the `char(36)` or is that strictly a Doctrine GUID thing?

**Comment by BallisticPain** [comment]
I may have just answered my own question if you indicate you're relying on GUID.

http://doctrine-dbal.readthedocs.org/en/latest/reference/types.html#guid

Thoughts?

**Comment by ramsey** [comment]
I might be wrong, but I think the PostgreSQL internal type of UUID is used to allow the database to generate the UUIDs for you. I've never used it, so let me know if that's not the case. And Doctrine's GUID type allows Doctrine to set the database engine's field to its internal identifier (whether it's UUID, GUID, etc.). My Doctrine and ramsey/uuid connector simply allows UUIDs in the database to be mapped into Ramsey\Uuid objects.

I'm not sure that answers your question. I'll need to look into Doctrine's GUID and PostgreSQL's UUID type a bit more.

**Comment by BallisticPain** [comment]
@ramsey 

I think that they map even in MySQL appropriately and then to a char(36) when/where there's not a native type. At least that's what I feel I gleaned from the above linked documents!

Thanks for taking the time to answer!

**Comment by teohhanhui** [comment]
Indeed with PostgreSQL, the `uuid` database tyoe is already being used: https://github.com/doctrine/dbal/blob/v2.6.3/lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php#L956-L962
