### ISSUE TITLE
unable to change factory

### ISSUE THREAD

**Issue by darkorsa** [ramsey/uuid-doctrine#86]
Although the [Ramsey\Uuid](https://github.com/ramsey/uuid) library gives you full freedom to exchange generators and replace for example _SystemNodeProvider_ with _RandomNodeProvider_, here you are doomed to default settings that use the _passthru_ function, which is disabled on my server for security reasons.

The solution would be if you could set your own Factory, but at the moment it is not possible. The constructor is final private and the _getUuidFactory_ method is private.

I know that you are trying to close objects to inappropriate changes, but could you do the _getUuidFactory_ method at least protected? Many people work with this code in different environments and such restrictions can be frustrating.

**Comment by ramsey** [comment]
I think it's reasonable to set both `getUuidFactory()` and `getCodec()` to `protected` or `public`. Would you like to make a pull request for this? If not, I can try to put something together soon.

Thanks!

**Comment by darkorsa** [comment]
I set both to protected since those methods are not part of the interface but are used by other methods within the class.

**Comment by darkorsa** [comment]
Hi @ramsey, is there a hope for accepting pull request in predictible timestamp?

**Comment by ramsey** [comment]
I’m sorry for the delay in accepting this. I’ll try to get caught up on pull requests and issues over the next few weeks. Thank you for your patience!

**Comment by darkorsa** [comment]
Hi @ramsey, Christmas are coming, miracles happen, so maybe also some accepting of PR's? ;)

**Comment by ramsey** [comment]
It’s on my list of things to review and merge during downtime over the holidays. Thanks for the reminder!

**Comment by ramsey** [comment]
Merged #87. Will release a new version soon. Thanks!
