### ISSUE TITLE
Zend Framework 2 Integration

### ISSUE THREAD

**Issue by humphrey09** [ramsey/uuid-doctrine#9]
This is rather a question than an issue:

I would like to use the 'ramsey/uuid-doctrine' plugin with Zend Framework 2 and Doctrine 2.

I cannot find sufficient information where to put the field type configuration as Doctrine 2 does not have a classic bootstrap.php within a ZF2 project setup.

The global, local and module config files in ZF2 are array structures which will not accept a field type configuration like shown in the readme.

Where should the following lines from the readme be placed within in the ZF2 project so that the field type 'uuid' is available?

```
\Doctrine\DBAL\Types\Type::addType('uuid', 'Ramsey\Uuid\Doctrine\UuidType');
$entityManager->getConnection()->getDatabasePlatform()->registerDoctrineTypeMapping('uuid', 'uuid');
```

Source:
https://github.com/ramsey/uuid-doctrine/blob/master/README.md

Any help would be greatly appreciated!

**Comment by WouterSioen** [comment]
As @Ocramius works on both ZF and Doctrine, he probably knows the answer to this.

**Comment by weierophinney** [comment]
I'd likely put it in you `Application\Module::onBootstrap()` method. You would grab the entity manager from the service manager first:

```php
public function onBootstrap($e)
{
    $app = $e->getApplication();
    $services = $app->getServiceManager();
    $entityManager = $services->get('Doctrine\ORM\EntityManager');
    \Doctrine\DBAL\Types\Type::addType('uuid', 'Ramsey\Uuid\Doctrine\UuidType');
    $entityManager->getConnection()->getDatabasePlatform()->registerDoctrineTypeMapping('uuid', 'uuid');
}
```

**Comment by gianarb** [comment]
Hello

I think that you can try this  solutionhttps://github.com/doctrine/DoctrineORMModule/blob/master/docs/configuration.md#how-to-add-new-type

**Comment by humphrey09** [comment]
Thank you very much for quick replies -  and especially for your suggestions, @weierophinney and @gianarb !

I tried both of them and they both work like a charm in the mentioned ZF2/Doctrine project setup!
I like the configuration way better, because it keeps the code clean.

Just for the sake of completeness, here are the important parts of the config file (in <PROJECT_ROOT>\config\autoload\doctrine.local.php), as suggested by @gianarb:

```
	return array(
			'doctrine' => array(
					'connection' => array(
							'orm_default' => array(
									'params' => array(
											'host' => $dbParams['hostname'],
											'port' => $dbParams['port'],
											'user' => $dbParams['username'],
											'password' => $dbParams['password'],
											'dbname' => $dbParams['database'],
											'driverOptions' => array(
													\PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8'
											),
									),
									'doctrine_type_mappings' => array(
											'uuid' => 'uuid'
									),							
							)
					),
					'configuration' => array(
							'orm_default' => array(
									'types' => array(
											'uuid' => 'Ramsey\Uuid\Doctrine\UuidType'
									)
							)
					),					
			)
	);
```
The blocks **doctrine_type_mappings** and **configuration** were added for the field type 'uuid'.

Again, thank you very much for your quick help!

**Comment by Ocramius** [comment]
@humphrey09 remember to use `::class` when pointing at existing classes/interfaces in configs: much easier to refactor ;-)

**Comment by humphrey09** [comment]
Hi @Ocramius,
Could you explain it a little more? I don't get the point with `::class`.
Sorry ;)

**Comment by Ocramius** [comment]
```php
'uuid' => 'Ramsey\Uuid\Doctrine\UuidType'
```
Becomes
```php
'uuid' => \Ramsey\Uuid\Doctrine\UuidType::class
```

**Comment by humphrey09** [comment]
Perfect, thanks :)
