### ISSUE TITLE
Extend GuidType instead of generic Type?

### ISSUE THREAD

**Issue by garak** [ramsey/uuid-doctrine#91]
I think that UuidType could extend [GuidType](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Types/GuidType.php) instead of Type.
It would save from re-declaring `getSQLDeclaration` method.
Moreover, comment can be skipped when native uuid is supported.

**Comment by ramsey** [comment]
This sounds reasonable to me. Let me know if you'd like to open a PR for this. Otherwise, I can add it to my list. 😄

**Comment by garak** [comment]
See #100
